---
title: "Investigación"
editor: visual
---

<link rel="stylesheet" href="style/estilo.css">

# Grupos de Investigación / Research groups

## Localización Continua 

### Coordinador: Víctor Blanco (Universidad de Granada)
 
La localización continua engloba aquellos problemas de localización de servicios donde el espacio de soluciones es continuo. Para analizar este tipo de problemas el grupo combina herramientas de análisis convexo, con aquellas de la optimización discreta y con el desarrollo de procedimientos iterativos de carácter geométrico. Las aplicaciones prácticas de la localización continua son el posicionamiento de sensores o cámaras donde hay cierta flexibilidad para su ubicación. La representación de los problemas como modelos de optimización sobre el cono de segundo orden combinados con las técnicas de optimización lineal entera es uno de los métodos más exitosos en esta área, y que debiera enriquecerse con el desarrollo de técnicas de ramificación-acotación-fijado-y-corte por desarrollar.

**Otros Miembros:** R. Gázquez (UC3M), A. Japón (US), R. Salmerón, C. García T. García, A. Gaggero, M. Martinez, P. Domínguez (UGR), S. García-Quiles (Unviversidad Edimburgo), J. Linderoth, A. Del Pia, S. Wraight (U. Wisconsin-Madison)

## Localización Discreta 

### Coordinadora: Mercedes Landete (Universidad Miguel Hernández de Elche)
 
Los problemas de localización discreta de plantas consisten en decidir sobre qué elementos elegir de entre un conjunto finito de posibilidades que minimicen cierto coste asociado con la ubicación y la instalación del servicio. Las técnicas más usadas para su análisis son las derivadas de la optimización discreta (ramificación y acotación, desigualdades válidas, poliédrica, relajación Lagrangeana). Uno de los objetivos del grupo es la extensión de los modelos de plantas a modelos de optimización en subastas, en cadenas de suministro, en modelos de planificación de la producción, etc.

**Otros miembros:** J. Alcaraz, M. Landete, JF. Monge, JL. Sainz-Pardo, M. Leal, L Antón, A Moya (UMH), Juan José Peiró (UV), F. Saldanha (Universidad de Sheffield)

## Localización bajo Competencia e Incertidumbre 

### Coordinador: Blas Pelegrín (Universidad de Murcia)

La localización de las instalaciones de una empresa es una decisión estratégica a la que se añaden otras decisiones tácticas con información posiblemente incierta.  En los últimos años se han desarrollado diversos modelos para incorporar y resolver problemas de localización en los que se incorporan elementos inciertos o en los que hay competencia en distintos escenarios definidos en por el comportamiento de los consumidores, el tipo de servicio, etc. Algunos modelos de interés en el análisis de la competencia son el modelo del seguidor, y el modelo del líder. Los modelos posibles que permiten incorporar la incertidumbre son numerosos, desde modelos robustos, a modelo con información probabilística básicos, a aquellos que contemplan conjuntos de fiabilidad y el CVar. La complejidad creciente de este tipo de problemas hace necesario el desarrollo de nuevos modelos, así como de nuevas técnicas de optimización que permitan gestionar de un gran número de datos.

**Otros Miembros:** J. Fernández, P. Fernández (UM), P. Martínez, J.  López (UA), I. Dorta (ULL), C. Manrique, P. Dorta, R. Suarez, D. Santos (ULPGC), E. Hendrix (UMA), J. Elizalde (UN), D.Ruiz (Sheffield University), BG. Toth (U of Szeged), A Alonso, D. Heredia, L Escudero (URJC), Celeste Pizarro (UCM)


## Diseño de Redes

### Coordinadora: Maria Albareda (Universidad Politècnica de Catalunya)
 
El diseño de redes estudia aquellos problemas de localización cuyo dominio es un grafo y en los que las decisiones de localización y asignación pueden asociarse a la selección de vértices y aristas. Entre sus principales aplicaciones destacan las telecomunicaciones y la logística de distribución, ámbitos en los que prácticamente cualquier decisión de carácter estratégico, táctico u operacional implica el diseño de la topología de una red. En este tipo de problemas es fundamental el uso de distintas herramientas de la Teoría de Grafos, combinada con la Optimización Combinatoria. Además, teniendo en cuenta la incertidumbre inherente a la mayoría de los problemas logísticos, es necesario el uso de herramientas de programación estocástica para su adecuado análisis.

**Otros Miembros:** JA. Iranzo (CUD), E. Codina, C. Núñez (UPC), H. Calvete, C. Galé (UZ), J. Rodríguez (UPF), G. Reinelt (Heidelberg U.), JA. Díaz (UDLA Puebla), R. Ríos, F. Camacho D. Huerta (UA Nuevo León)


## Rutas y Distribución 

### Coordinador: Juan José Salazar (Universidad de La Laguna)

Todos los aspectos que conciernen a los problemas de distribución y transporte son de gran importancia económica. Este grupo cubre el análisis y el desarrollo de métodos para la planificación, gestión y explotación de las redes de distribución y transporte de mercancías. Su propósito es ayudar a que el proceso de análisis y de toma de decisiones sea más eficaz y de mayor calidad. Se estudian diferentes problemas de rutas de vehículos y su combinación con los de localización de servicios, con especial énfasis en: i) problemas en los que la demanda se sitúa en los vértices que son extensiones de otros problemas conocidos, con aplicaciones más realistas, que permitan tener en cuenta las nuevas formas de distribución y recogida de mercancías, ii) problemas en los que la demanda se sitúa en los arcos que incorporen consideraciones referentes al eventual beneficio de la operación, a las relacionadas con los costes y sobre diferentes tipos de grafos, iii) problemas relacionados con rutas inteligentes para un transporte sostenible e integrado.

**Otros Miembros:** H. Hernández, J. Riera I. Rodríguez (ULL), A. Santini (UPF), JM. Sanchís (UPV), E. Benavent (UV), Miguel Reula, P. Segura (UV).

## Ciencia de Datos y Localización: 

### Coordinador: Antonio M Rodríguez Chía (Universidad de Cádiz)

En los últimos años, el avance de las herramientas computacionales para resolver exactamente problemas de optimización complejos, así como aquellas relacionadas con el manejo de grandes bases de datos, han abierto un campo de trabajo de muy alta repercusión en el Análisis de Datos moderno en lo que se refiere a modelos de optimización para la construcción de herramientas de aprendizaje automático con distintas particularidades, que hasta el momento no eran posibles por las limitaciones computacionales y de modelado matemático. En este sentido, recientemente el grupo de trabajo ha detectado una conexión directa entre los problemas clásicos de localización y la construcción de herramientas de clasificación supervisada. El desarrollo de modelos de aprendizaje automático que permitan extraer información relevante de los datos, y de algoritmos eficientes y escalables de resolución, que se adapten a las necesidades de los datos, con criterios de interpretabilidad, equidad, capacidad de inferencia, y transparencia, son algunos de los objetivos del grupo.

**Otros Miembros:**  A. Castaño, M. Baldomero, I. Espejo, L. Martínez, JM Muñoz,  T. Navarro, R. Páez, C. Valero (UCA), S. Nickel (Karlsruhe Ins. of Tech), J. Kalsics (Univ. Edimburgh).

## Localización y análisis de redes complejas e inteligencia artificial 

### Coordinador: Justo Puerto (Universidad de Sevilla)

La integración de diferentes elementos relevantes en el análisis de los problemas de localización, como el inventario, la secuenciación de tareas, o la gestión de colas, que de forma clásica no se habían considerado simultáneamente, genera modelos usualmente muy complejos pero que en contrapartida representan con mayor fidelidad la situación bajo estudio. El objetivo es crear modelos matemáticos realistas, que ayuden de manera eficaz a la toma de decisiones y a la monitorización de estos sistemas. Para conseguir dicho objetivo será necesario trabajar en varias líneas de acción, algunas de ámbito local que analicen propiedades específicas y que innoven en el tratamiento de problemas concretos, y otras más globales que incorporen las innovaciones específicas en el desarrollo de algoritmos de resolución para problemas de mayor entidad. Este es el caso de la conexión con la Inteligencia Artificial, tanto para el desarrollo de herramientas eficientes de resolución para sistemas de grandes tamaños, como para el diseño de sistemas inteligentes usando herramientas de la gestión logística. El principal objetivo en conjunción con todas estas es la aplicación de los resultados obtenidos a la gestión de las redes en problemas urbanos (smart cities). Todos estos factores se relacionan por la capacidad de resolver problemas nuevos y utilizar herramientas matemáticas para mejorar su eficiencia.

**Otros Miembros:** Y. Hinojosa, M. Pozo, D. Ponce, *M. Rodriguez*, A. Torrejón, F Temprano, G Gonzalez (US),  D. Pérez (ULL), S. Benati (U. Trento), A. Scozzari (U. degli Studi Niccolò Cusano), L. Amorosi, F. Ricca (U La Sapienza).

## Localización de Concentradores y Logística Portuaria 

### Coordinadora: Elena Fernández (Universidad de Cádiz)

A camino entre la localización y los problemas de rutas están los problemas de localización de concentradores (hubs) y aquellos de gestión logística en puertos. El auge de los últimos años, tanto por el desarrollo de modelos y técnicas como en las importantes aplicaciones a nivel logístico que tienen, le han dado un lugar privilegiado en el estudio de este tipo de sistemas logísticos. La combinación de rutas, con decisiones de diseño, hacen de estos problemas un gran reto a nivel matemático, tanto desde el punto de vista del modelado como de su resolución eficiente. El grupo ha liderado propuestas con una gran repercusión internacional, y que han afectado a cómo se gestionan actualmente muchos de estos modelos . La construcción de modelos realistas, el estudio poliédrico de los problemas de programación lineal entera que se derivan, el diseño de estrategias de ramificación, corte y pricing para la resolución eficiente de los problemas, son algunos de los objetivos de este grupo.

**Otros Miembros:** M Muñoz, M Arana, CA Domínguez, N Zerega (UCA), I. Ljubic, C. Archetti, D (ESSEC)

## Gestión Óptima del Transporte 

### Coordinador: David Canca (Universidad de Sevilla)
 
Uno de los mayores éxitos de la Investigación Operativa y otras áreas de la Matemática Aplicada ha sido la aplicación de sus modelos y métodos de resolución en el campo de la planificación en transportes. Por otra parte, este campo genera problemas, a menudo muy complejos, que inspiran nuevas metodologías de modelación y resolución. Quizás el área más importante de la planificación en transportes es la de los pasajeros. Diariamente millones de personas se mueven en transportes colectivos entre ciudades o en áreas metropolitanas. La organización eficiente de los recursos para la movilidad requiere el uso de sofisticadas metodologías matemáticas. En particular, el Análisis de Localizaciones proporciona modelos y métodos de resolución para localizar los puntos de acceso y la conexión entre los mismos, en los sistemas de transporte. La Ciencia de la Localización proporciona metodologías y otras herramientas a la resolución de los problemas de la operación de los sistemas de transporte.

**Otros Miembros:** JA Mesa, F. Ortega, F. Perea, A. De los Santos, R. Piedra, N. Gonzalez-Blanco, G. Marseglia, M. Calvo, PL González, M. Calle-Suárez, JL Andrade, JM Leon Blanco, MC. Lopez de los Mozos (US), E. Barrena (UPO), A. Zarzo (UPM).

## Logística Humanitaria

### Coordinadora: Teresa Ortuño (Universidad Complutense de Madrid)
 
La logística humanitaria es un tipo de logística enfocada a aliviar el sufrimiento de las personas vulnerables. Estas características específicas se pueden agrupar en tres grandes rasgos: decisores, objetivos estratégicos e incertidumbre. Las metas estratégicas y las medidas de desempeño de la logística humanitaria también son específicas, siendo la prioridad más característica la eficacia (sobre la eficiencia). Es por esto, que, al diseñar modelos de apoyo a la decisión en este contexto, es importante tener en cuenta que un logístico humanitario no puede valorar sólo económicamente el logro de objetivos. Además, la incertidumbre y la presión del tiempo son variables que determinan el entorno en el que se deben tomar decisiones, con alta relevancia durante la gestión de un desastre. El gran reto de este grupo es el desarrollo de modelos de decisión que integrados con los sistemas de información disponibles den respuesta a las distintas fases de la gestión de desastres.

**Otros Miembros:** G Tirado, JM Ferrer, A. Rodríguez, B. Vitoriano, J Martin-Campo, B. Granada, J. León, J. Barreal (UCM), Federico Liberatore (Cardiff University)

